import { Inter, Rye } from "next/font/google";
import "./globals.css";

const rye = Rye({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rye.className} bg-[#FDFF75] overflow-y-scroll overflow-x-hidden`}>{children}</body>
    </html>
  );
}
